State machine
cornellhyperloop/electrical pull request #222
Opened 2022-10-13 16:48 UTC by ridhitbhura

Merge state_machine branch to master branch

2022-10-13 19:50 UTC, davidsw34 reviewed
lgtm. But let's have @roninsharma25  review it too since there are changes to the JSON that the UI team would read from

2022-10-13 23:53 UTC, roninsharma25 approved these changes
LGTM!

2022-10-24 22:12 UTC, roninsharma25 requested changes

2022-10-24 22:12 UTC, roninsharma25 commented on Communications/Communications_Code/subscribe.c
> +	fprintf(fp, "\n");
test comment

2022-10-24 22:12 UTC, roninsharma25 commented on Communications/Communications_Code/subscribe.c
> -			fprintf(fp, "\"Temperature\" : \n{");
why''d you remove this line

2022-10-25 00:05 UTC, roninsharma25 approved these changes

2022-11-07 22:03 UTC, merged