Graphics2
cornellhyperloop/electrical pull request #256
Opened 2022-10-27 22:45 UTC by christinaunk

2022-10-28 00:30 UTC, roninsharma25 requested changes
My only feedback is that you don't want to commit the `gui_env` folders

2022-10-28 00:42 UTC, KelvinLWang approved these changes

2022-10-31 19:26 UTC, ryanwmao reviewed
Can add gui_env to gitignore so that it won't be pushed to github

2022-10-31 22:08 UTC, ryanwmao approved these changes

2022-11-07 19:45 UTC, roninsharma25 approved these changes

2022-11-07 22:07 UTC, merged