Export as graph PNG
cornellhyperloop/electrical pull request #262
Opened 2022-10-31 19:21 UTC by ryanwmao

Example in Graph.png

2022-10-31 19:46 UTC, roninsharma25 requested changes
Could you also add something that notifies the user that the graph has been downloaded? Currently, nothing happens so a user might not know what happens. One option is to have a popup similar to how the help button currently operates. Since this feature wasn't part of the initial task description, feel free to create a new task for the feature.

2022-10-31 19:46 UTC, roninsharma25 commented on GUI/widgets/plot_buttons.py
> +        #     self.plot.frameGeometry().width(), self.plot.frameGeometry().height()
Can you delete these lines if they aren't used?

2022-10-31 19:46 UTC, roninsharma25 commented on GUI/widgets/plot_buttons.py
> +        # self.exporter.export('Graph.png')
This can be deleted as well

2022-10-31 19:46 UTC, roninsharma25 commented on GUI/widgets/plot_buttons.py
> +        self.plot.getPlotItem().writeImage("Graph.png")
Do we want the filename to be in the constants file?

2022-11-07 17:37 UTC, ryanwmao commented
Created new task for button, i think it applies to a couple other buttons on GUI as well (#271)

2022-11-07 17:42 UTC, KelvinLWang approved these changes

2022-11-07 19:21 UTC, roninsharma25 approved these changes

2022-11-07 19:57 UTC, merged