changed to gridlayout and fix widgets not showing
cornellhyperloop/electrical pull request #277
Opened 2022-11-08 00:55 UTC by KelvinLWang

2022-11-08 20:37 UTC, ryanwmao approved these changes
looks good, maybe comments deleted

2022-11-09 06:22 UTC, roninsharma25 requested changes

2022-11-09 06:22 UTC, roninsharma25 commented on GUI/utils/header.py
> +        # grid1.addWidget(self.pBar, 0, 1, alignment=Qt.AlignCenter)
These can be deleted

2022-11-09 06:22 UTC, roninsharma25 commented on GUI/utils/header.py
> +        # splitter4.setSizes([int(self.height / 30), int(self.height / 30)])
These can also be deleted

2022-11-09 06:22 UTC, roninsharma25 commented on GUI/widgets/plot_buttons.py
> +        self.reset_plot_button.setStyleSheet(
Can you notify the people working on the CSS ticket about these changes? Not sure if they already branched off.

2022-11-10 05:02 UTC, chp36 approved these changes

2022-11-12 19:32 UTC, aislinnennis approved these changes

2022-11-14 19:41 UTC, roninsharma25 approved these changes

2022-11-27 02:04 UTC, merged